/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as GettingStartedInstallationImport } from './routes/getting-started/installation'
import { Route as ExamplesThatImport } from './routes/examples/that'
import { Route as ExamplesBasicImport } from './routes/examples/basic'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const GettingStartedInstallationRoute = GettingStartedInstallationImport.update(
  {
    id: '/getting-started/installation',
    path: '/getting-started/installation',
    getParentRoute: () => rootRoute,
  } as any,
)

const ExamplesThatRoute = ExamplesThatImport.update({
  id: '/examples/that',
  path: '/examples/that',
  getParentRoute: () => rootRoute,
} as any)

const ExamplesBasicRoute = ExamplesBasicImport.update({
  id: '/examples/basic',
  path: '/examples/basic',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/examples/basic': {
      id: '/examples/basic'
      path: '/examples/basic'
      fullPath: '/examples/basic'
      preLoaderRoute: typeof ExamplesBasicImport
      parentRoute: typeof rootRoute
    }
    '/examples/that': {
      id: '/examples/that'
      path: '/examples/that'
      fullPath: '/examples/that'
      preLoaderRoute: typeof ExamplesThatImport
      parentRoute: typeof rootRoute
    }
    '/getting-started/installation': {
      id: '/getting-started/installation'
      path: '/getting-started/installation'
      fullPath: '/getting-started/installation'
      preLoaderRoute: typeof GettingStartedInstallationImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/examples/basic': typeof ExamplesBasicRoute
  '/examples/that': typeof ExamplesThatRoute
  '/getting-started/installation': typeof GettingStartedInstallationRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/examples/basic': typeof ExamplesBasicRoute
  '/examples/that': typeof ExamplesThatRoute
  '/getting-started/installation': typeof GettingStartedInstallationRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/examples/basic': typeof ExamplesBasicRoute
  '/examples/that': typeof ExamplesThatRoute
  '/getting-started/installation': typeof GettingStartedInstallationRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/examples/basic'
    | '/examples/that'
    | '/getting-started/installation'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/examples/basic'
    | '/examples/that'
    | '/getting-started/installation'
  id:
    | '__root__'
    | '/'
    | '/examples/basic'
    | '/examples/that'
    | '/getting-started/installation'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExamplesBasicRoute: typeof ExamplesBasicRoute
  ExamplesThatRoute: typeof ExamplesThatRoute
  GettingStartedInstallationRoute: typeof GettingStartedInstallationRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExamplesBasicRoute: ExamplesBasicRoute,
  ExamplesThatRoute: ExamplesThatRoute,
  GettingStartedInstallationRoute: GettingStartedInstallationRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/examples/basic",
        "/examples/that",
        "/getting-started/installation"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/examples/basic": {
      "filePath": "examples/basic.tsx"
    },
    "/examples/that": {
      "filePath": "examples/that.tsx"
    },
    "/getting-started/installation": {
      "filePath": "getting-started/installation.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
